@Bloga_HostAddress = http://localhost:5088/api

// - POSTS
GET {{Bloga_HostAddress}}/posts/
Accept: application/json

###
GET {{Bloga_HostAddress}}/posts/2

###
POST {{Bloga_HostAddress}}/posts
Content-Type: application/json

{
    "title":"test title 12",
    "content":"this is another test content",
    "categoryId":3,
    "tags":["C#","Entity Framework Core","SQL"]
}

###

PATCH  {{Bloga_HostAddress}}/posts/16
Content-Type: application/json

{
    "title":"test title 2-edited",
    "content":"this is another test content",
    "categoryId":null,
    "tags":["C#","Entity Framework Core","SQL"]
}

###
DELETE {{Bloga_HostAddress}}/posts/2


// - CATEGORIES
###
GET {{Bloga_HostAddress}}/categories
Accept: application/json

###
GET {{Bloga_HostAddress}}/categories/3

###
POST  {{Bloga_HostAddress}}/categories
Content-Type: application/json

{
    "name":"Career"
}
###